### ISSUE TITLE
IoT Central Rest Api

### ISSUE THREAD

**Issue by TheNomanAhmed** [jimbobbennett/IoTUglySweater#2]
I would really like to see an example to use IoT Central REST api.

**Comment by jimbobbennett** [comment]
For which part? Do you mean nstead of a logic app to control the sweater?

**Comment by TheNomanAhmed** [comment]
Yes @jimbobbennett

**Comment by jimbobbennett** [comment]
We have some great docs on this process - https://docs.microsoft.com/rest/api/iotcentral/. It's a bit complicated due to the authentication, so if this interested you I suggest starting with these docs. If you want to write it up and create a PR for this to add REST instructions as well, that would be great!
